BaseMatrix
UInt BaseMatrix< T >::rows
Referenced by Array< UInt >::resize, BaseMatrix< UInt >::BaseMatrix, BaseMatrix< UInt >::resize, BaseMatrix< UInt >::nbRows, BaseMatrix< UInt >::size, Matrix< double >::resize, Matrix< double >::operator().
UInt BaseMatrix< T >::cols
Referenced by Array< UInt >::Array, Array< UInt >::resize, Array< UInt >::operator(), BaseMatrix< UInt >::BaseMatrix, BaseMatrix< UInt >::resize, BaseMatrix< UInt >::nbCols, BaseMatrix< UInt >::size, Matrix< double >::Matrix, Matrix< double >::resize.
std::vector<T> BaseMatrix< T >::storage
Referenced by Array< UInt >::resize, Array< UInt >::operator(), Array< UInt >::operator=, BaseMatrix< UInt >::storageSize, BaseMatrix< UInt >::getStorage, Matrix< double >::resize, Matrix< double >::operator(), Matrix< double >::operator/=, Matrix< double >::operator*=, Matrix< double >::operator+=, Matrix< double >::operator=.
BaseMatrix< T >::BaseMatrix()=default
BaseMatrix< T >::BaseMatrix(UInt rows, UInt cols)
virtual BaseMatrix< T >::~BaseMatrix()=default
virtual void BaseMatrix< T >::resize(UInt rows, UInt cols)
Referenced by BaseMatrix< UInt >::BaseMatrix, Matrix< double >::resize, Array< UInt >::resize.
virtual T& BaseMatrix< T >::operator()(UInt i, UInt j)=0
virtual T BaseMatrix< T >::operator()(UInt i, UInt j) const =0
virtual void BaseMatrix< T >::print(std::ostream &stream) const
Referenced by operator<<.
UInt BaseMatrix< T >::nbRows() const
Referenced by DispElement::DispElement, DispElement::GetStiffnessAndRes, PhaseElement::GetStiffnessAndRes, operator*, operator+, operator-, PhaseElement::PhaseElement, Model::set_init.
UInt BaseMatrix< T >::nbCols() const
Referenced by operator*, operator+, operator-, Model::set_init.
UInt BaseMatrix< T >::size() const
Referenced by BaseMatrix< UInt >::print, Array< UInt >::resize, Matrix< double >::resize, NRsolver::solve.
UInt BaseMatrix< T >::storageSize() const
Referenced by BaseMatrix< UInt >::print.
std::vector<double>& BaseMatrix< T >::getStorage()
Referenced by PhaseElement::GetStiffnessAndRes.
std::ostream& operator<<(std::ostream &stream, const BaseMatrix< T > &_this)
Output to stream.