Matrix
using Matrix< T >::Parent = BaseMatrix<T>
Matrix< T >::Matrix()=default
Matrix< T >::Matrix(UInt rows, UInt cols)
Matrix< T >::~Matrix()=default
void Matrix< T >::resize(UInt rows, UInt cols)
Referenced by DispElement::DispElement, Matrix< double >::inverse, Matrix< double >::Matrix, PhaseElement::PhaseElement, Matrix< double >::transpose.
T& Matrix< T >::operator()(UInt i, UInt j)
T Matrix< T >::operator()(UInt i, UInt j) const
Matrix<T>& Matrix< T >::operator/=(const T &c)
Matrix<T>& Matrix< T >::operator*=(const double &c)
Matrix<T>& Matrix< T >::operator+=(const Matrix< T > &a)
Matrix<T>& Matrix< T >::operator=(T c)
void Matrix< T >::transpose(Matrix< T > &)
Referenced by DispElement::GetStiffnessAndRes, PhaseElement::GetStiffnessAndRes.
void Matrix< T >::inverse(Matrix< T > &)
Referenced by DispElement::GetStiffnessAndRes, PhaseElement::GetStiffnessAndRes, NRsolver::solve.
double Matrix< T >::determinant()
Referenced by DispElement::GetStiffnessAndRes, PhaseElement::GetStiffnessAndRes, Matrix< double >::inverse.
void Matrix< T >::print(std::ostream &stream) const
standard output stream operator