Array
using Array< T >::Parent = BaseMatrix<T>
Array< T >::Array()=default
Array< T >::Array(UInt rows, UInt cols)
Array< T >::~Array()=default
void Array< T >::resize(UInt rows, UInt cols)
Referenced by Array< UInt >::Array, Model::readInput, Model::set_init.
T& Array< T >::operator()(UInt i, UInt j)
T Array< T >::operator()(UInt i, UInt j) const
Array<T>& Array< T >::operator=(T c)
void Array< T >::print(std::ostream &stream) const
standard output stream operator