project = 'Phase-field FE'


#...
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.intersphinx',
    'sphinx.ext.coverage',
    'sphinx.ext.mathjax',
    'sphinx.ext.ifconfig',
    'sphinx.ext.viewcode',
    'sphinx.ext.graphviz',
    'sphinx.ext.inheritance_diagram',
    'breathe' ]

# setting the theme for html pages
html_theme = 'sphinx_rtd_theme'

# source file extension to read
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# syntax highlighting style to use 
pygments_style = 'sphinx'

primary_domain = 'cpp'

highlight_language = 'cpp'

# Breathe Configuration
breathe_default_project = "Phase-field FE"

# Number figures
numfig = True
